apiVersion: v2
name: galato
description: A production-grade Web3 infrastructure management system with RaaS capabilities
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com
keywords:
  - web3
  - infrastructure
  - kubernetes
  - rollup
  - blockchain
home: https://github.com/yourusername/galato
sources:
  - https://github.com/yourusername/galato
dependencies:
  - name: prometheus
    version: "15.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: "6.0.0"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: cert-manager
    version: "1.0.0"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled 